### ISSUE TITLE
When will the new version come out?

### ISSUE THREAD

**Issue by Herwork06** [vaphes/pocketbase#12]
Hi!
I am using pocketbase but I coded a project in python and I didn't want to move over to js or ts. So I found this package but the released version is old and I want to get the newer version of it. But is the beta version still in the testing process or is it done?

**Comment by vaphes** [comment]
Hi @Herwork06, I'll be updating the pipy repository this week, we are a very small group of contributors at moment with very little time available (at least by my part). Feel free to make any suggestions and pull requests if you find something not working properly. Thanks.
