### ISSUE TITLE
update to pocketbase version 0.8.0-rc1

### ISSUE THREAD

**Issue by perfalle** [vaphes/pocketbase#2]
This weekend, pocketbase:0.8.0-rc1 was released for testing and it comes with some breaking changes in its API.
Therefore the client SDKs have to update, too.

I have already worked on the updated python sdk in a fork of this repo and I want to create a pull request for my changes for you to check -> #3

**Comment by vaphes** [comment]
As replied in the request [#3] I created a new branch for the update and added you as a contributor. Welcome aboard!

**Comment by perfalle** [comment]
Cool, thank you :)
I have merged (#4) my changes to the 0.8.0-rc2 branch.
