### ISSUE TITLE
[Question] Unable to run simple query to fetch a document from a collection

### ISSUE THREAD

**Issue by ryanrosello-og** [vaphes/pocketbase#24]
Hi, I have this collection containing the following docs:

![image](https://user-images.githubusercontent.com/50574915/218240785-4ae9db27-36cf-4b1a-8356-f7992d276c19.png)

I'm trying to fetch an article where exhausted === False

```
# fetch a test article where exhausted is false
article = client.collection("articles").get_list(
    1, 20, {"filter": 'exhausted = false"'})
print('article', article.items[0])
```

but it keeps failing here?

```
ne 37, in _get_list
    response_data = self.client.send(
                    ^^^^^^^^^^^^^^^^^
  File "C:\_repo\python_pocket_base\.venv\Lib\site-packages\pocketbase\client.py", line 109, in send
    raise ClientResponseError(pocketbase.utils.ClientResponseError: Response error. Status code:403
```

Have I used the correct syntax to fetch?

**Comment by ryanrosello-og** [comment]
Thanks, yeah that was it 🤦 

I did not set this rule to 'Set custom rule'

![image](https://user-images.githubusercontent.com/50574915/218242567-b9814e9f-44da-429d-bd0e-7d93476fdce6.png)

**Comment by bobwatcherx** [comment]
how to fetch and see data like this 
root@minx-Lenovo-V145-14AST:/home/minx/belajar/colongan/pythonsidik# python3 test.py 
<Record: 85oeuawmpqdm44y>
<Record: l99wjn9094c2193>

my code 
import asyncio
from pocketbase import PocketBase

client = PocketBase('http://127.0.0.1:8090')


admin_data = client.admins.auth_with_password("xxx@gmail.com", "admxxxxin12345")

result = client.collection("fletSample").get_full_list()

for x in result:
	print(x)
