### ISSUE TITLE
how to Add record to collection 

### ISSUE THREAD

**Issue by bobwatcherx** [vaphes/pocketbase#30]
i want to add data to collection
my code
record = client.collection('fletSample').create(name="bout",age=120)

BUT ERROR
  File "/home/minx/belajar/colongan/pythonsidik/test.py", line 7, in <module>
    record = client.collection('fletSample').create(name="bout",age=120)
TypeError: CrudService.create() got an unexpected keyword argument 'name'

wahst solutions

**Comment by paulocoutinhox** [comment]
You can read the readme or tests:

```
result = client.collection("fletSample").create({
        "name": "bout",
        "age": 120
})
```
