### ISSUE TITLE
Run background 

### ISSUE THREAD

**Issue by elsacutealways** [vaphes/pocketbase#34]
How to run subscribe() forever?

**Comment by PFcs50** [comment]
I apologize if this isnt proper etiquite as I dont use gitbhub often but I am in dire need of help in regards to subscribe() and was wondering if you are able to share how you got it to work temporarily? I for the life of me can not figure out how to handle to callback argument requirement and there is very little discussion online about pocketbase in general nevermind this package.

**Comment by m29h** [comment]
A very _naive_ example how subscribing is done is the following
Note that this obviously assumes you have a collection with id = coll_id that has a record field called "title".

```python 
c = client.collection(coll_id)
def callback(e: MessageData):  ##this will be called completely out-of-order whenever an event happens in pocketbase
    print(e.record.title)   
c.subscribe(callback)
sleep(0.1)
for _ in range(10)
    c.create({"title": "Hello World")   ## create a record (even an create in a completely different client will trigger above event)
    sleep(1)
```

I hope this helps. Note that unsusbscribe() currently has a bug #45 but the subscribe() method should work fine like above.

**Comment by m29h** [comment]
Closed due to inactivity
