### ISSUE TITLE
Client Deserializes Record Values to `collection_id` Attribute

### ISSUE THREAD

**Issue by Dan6erbond** [vaphes/pocketbase#37]
I'm trying to fetch a record with a file, so I can use the `client.get_file_url()` method on it. I immediately noticed in the debugger, that all the record's values are being deserialized to `collection_id` which is most likely an error. 

<img width="757" alt="image" src="https://github.com/vaphes/pocketbase/assets/32235074/fe0882ce-c8ad-4069-8f74-b182fecdd4e9">

My code:

```py
    record = client.collection("files").get_one(file_id)
    url = client.get_file_url(record, record.collection_id["file"], {})
```

**Comment by stratosgear** [comment]
I've also commented in the MR too, but here might make more sense. Sorry for duplicate message :(

Fix works for me.

When can we expect a release? This is a major broken release that is out there now!

Thanks, btw!!!
