### ISSUE TITLE
version 0.8.2 actually isn't in pypi

### ISSUE THREAD

**Issue by mezerotm** [vaphes/pocketbase#55]
I saw 0.8.2 came out 3 days ago, and the pypi has updated it's version and name, but looking at the source dist, and the built dist. it's missing some of the changes made for example #43 (A feature I wanted from this version)

**Comment by m29h** [comment]
the version 0.8.2 in pypi is definitively identical to the release here in the repository!
however the release [v0.8.2](https://github.com/vaphes/pocketbase/tree/v0.8.2) is based on the commit hash https://github.com/vaphes/pocketbase/commit/4ff17b4cf0a4ec64a7c620b6dba4c4a0e9005b7e meanwhile issue #43 was unfortunately only commited afterwards. So #43 is only solved in the `master` branch but not in any release yet.

If you really want to be on the bleeding edge, you can try to directly install the git master branch in pip
`pip install git+https://github.com/vaphes/pocketbase.git@master`
