### ISSUE TITLE
TypeError when expanding relations.

### ISSUE THREAD

**Issue by kbruegge** [vaphes/pocketbase#65]
Hi there,

I've been trying to use `client.collection("foo").get_list` and `client.collection("foo").get_full_list` together with the `expand` query parameter.

See the documentation of the JS SDK here: https://pocketbase.io/docs/working-with-relations/#expanding-relations

Apparently the `load` method of the "BaseModel" class expects a dict but receives a list. I added some print statements.

    def load(self, data: dict) -> None:
        """Loads `data` into the current model."""
        print(data, type(data))
        self.id = data.pop("id", "")
        self.created = to_datetime(data.pop("created", ""))
        self.updated = to_datetime(data.pop("updated", ""))

Here is the output:
```
In [2]: client.collection("labels").get_list(1, 30, query_params={"expand": "location"})

{'collectionId': 'c2laxzj0zheqs0l', 'collectionName': 'labels', 'created': '2023-08-07 10:06:32.374Z', 'end': '2023-04-06 23:30:00.000Z', 'expand': {'location': [{'collectionId': 'd4jq751z03smpzz', 'collectionName': 'pump_parts', 'created': '2023-08-07 08:52:03.363Z', 'id': '0yoeep2hyh0p57t', 'name': 'WB2', 'updated': '2023-08-07 08:52:03.363Z'}]}, 'id': '1hiin4yc2mzi5dd', 'label': ['l38hfht79whweza'], 'location': ['0yoeep2hyh0p57t'], 'monitoring_id': 18198, 'start': '2023-04-06 18:05:00.000Z', 'updated': '2023-08-07 10:06:32.374Z'} <class 'dict'>
[{'collectionId': 'd4jq751z03smpzz', 'collectionName': 'pump_parts', 'created': '2023-08-07 08:52:03.363Z', 'id': '0yoeep2hyh0p57t', 'name': 'WB2', 'updated': '2023-08-07 08:52:03.363Z'}] <class 'list'>
```

Which further results in the following exception

```
File <path>/pocketbase/models/utils/base_model.py:27, in BaseModel.load(self, data)
     25 """Loads `data` into the current model."""
     26 print(data, type(data))
---> 27 self.id = data.pop("id", "")
     28 self.created = to_datetime(data.pop("created", ""))
     29 self.updated = to_datetime(data.pop("updated", ""))

TypeError: pop expected at most 1 argument, got 2
```

Thanks for working on this by the way!

**Comment by czwilling** [comment]
I can confirm this. 
A fix would be great.

**Comment by kbruegge** [comment]
One thing I forgot to mention. The relation can point to multiple rows in the other collection. See the attached screenshot from the PocketBase  admin interface. 

<img width="656" alt="Screenshot 2023-08-09 at 13 21 35" src="https://github.com/vaphes/pocketbase/assets/4076745/f47375e5-b648-4f77-aa5b-219edf5db662">

**Comment by m29h** [comment]
Relation expansion had a working integration test [here](https://github.com/vaphes/pocketbase/blob/master/tests/integration/test_record.py#L82)

I can see that this currently only works for a single record relation.

Can you confirm that your issue is caused only when there is a 'multi' relationship to a 'list of multiple record' relationships?

**Comment by m29h** [comment]
Now the value of Record.expand["xxx"] can either be
- key "xxx" not present in the map expand at all if there is no relation stored for the Record
- a value of type Record if there actually is a single relation (even if pocketbase theoretically allows to set more than one relation)
- a value of type List[Record] if there are actually two or more relations

This is somewhat "highly dynamically typed" in a way 1:1 as it simply comes from pocketbase.

**Comment by kbruegge** [comment]
Hi. Thanks for the PR. I will test it once I get back to work next tuesday.

**Comment by kbruegge** [comment]
PR #66 does indeed fix it. Thank you.
