### ISSUE TITLE
Support for protected files

### ISSUE THREAD

**Issue by simon-lund** [vaphes/pocketbase#72]
Hello again ^^

does the SDK support protected files yet?
See here: https://pocketbase.io/docs/files-handling/#protected-files

I couldn't find the respective method in the SDK, but maybe I overlooked it?

**Comment by m29h** [comment]
Habe you tried doing the same thing like shown [here](https://github.com/vaphes/pocketbase/blob/master/tests/integration/test_files.py#L97) on your protected file.
My guess is that it works just out of the box. Every file in Pocketbase has always a sort of random id appended to the name. The only difference for protected files is that the random id will have a limited validity. This is enforced on the server side and should not need any explicit implementation on the client side.

(To refresh the ID you simply would call another get record query on the collection service and then pass the new result in the get_file_name method.

**Comment by simon-lund** [comment]
Hello, sorry I forgot to close this issues. I ended up imitating the [getToken function](https://github.com/pocketbase/js-sdk/blob/98b5fa014a27b88a6f25d39d741b10f821d0a24a/src/services/FileService.ts#L47) from the js-sdk with the `send(...)` method provided by the python-sdk. Afaik I need this token, otherwise it creates a permanent link.
