### ISSUE TITLE
Support backup API

### ISSUE THREAD

**Issue by slobberchops** [vaphes/pocketbase#86]
Any interest in supporting the backup API? It might be something I could contribute.

**Comment by vaphes** [comment]
> Any interest in supporting the backup API? It might be something I could contribute.

Hi @slobberchops , yes! It would be nice if you could implement it as I couldn't keep up with the js sdk lately. Thanks in advance.

**Comment by slobberchops** [comment]
Ok. I regret that my project switched to using Go for our CLI, however I will attempt to contribute something all the same.

The download endpoint will require additional work to support because of what goes on here: https://github.com/vaphes/pocketbase/blob/master/pocketbase/client.py#L111

In the case of download it will be necessary to allow the client to return the raw response from a service. I will restructure things one way, and you can tell me if is ok or you would prefer a different approach.

**Comment by slobberchops** [comment]
I have made a pull request here: https://github.com/vaphes/pocketbase/pull/87

I will obviously need assistance running the tests workflow... I will probably attempt to run them in my fork repository.

**Comment by slobberchops** [comment]
I have verified that test workflow runs and all tests pass for all supported Python versions.
